### ISSUE TITLE
About the next release

### ISSUE THREAD

**Issue by obynio** [gin-contrib/logger#4]
Hi !

I've seen that there is no release including the latest commits.

Could you consider tagging a new release to include them ?
It would be very useful to avoid issues like ambiguous import with the `ugorgi/codec` dependency 🙂 

Regards,

**Comment by obynio** [comment]
Hello @appleboy 

Any news on this matter ? 🙂

**Comment by xavier-rodet** [comment]
Yes please @appleboy !

This is really needed to avoid this ambiguous import ...

Also, i noticed in your go.sum you have `ugorji/go v1.1.4` when it should be `ugorji/go v1.1.7` (which is fixing ambiguous import)  ? (`gin-gonic/gin v1.4.0` is now requiring `ugorji/go v1.1.7`).

Meanwhile, is it possible to bypass this error to build a module @obynio ?

**Comment by appleboy** [comment]
See the new version [v0.0.2](https://github.com/gin-contrib/logger/releases/tag/v0.0.2)

**Comment by xavier-rodet** [comment]
Thanks 👍

**Comment by obynio** [comment]
Amazing \o/  Thanks !
