### ISSUE TITLE
Allow to configure writers different from zerolog.ConsoleWriter

### ISSUE THREAD

**Issue by pscheid92** [gin-contrib/logger#41]
**Use Case**
I want structured logging in JSON format (like the default `zerolog`) instead of the human-friendly `ConsoleWriter` format.

<br>

**Analysis**
The current implementation hard-codes a `ConsoleWriter`. Other configurations are overwritten.
https://github.com/gin-contrib/logger/blob/1a331599cf7b8a8745e4cd27286d316c01dd9877/logger.go#L60-L69

<br>

**Ideas**
 1. **Make the writer configurable**
    We could allow a user to overwrite the writer instead of hard-coding it. `ConsoleWriter` still could be a good fallback.

 2. **Allow configuration by `gin.Mode`**
     We could allow different configurations according to the selected mode. For instance one could set `ConsoleWriter` for `gin. DebugMode` but the default JSON-format writer for `gin.ReleaseMode`. Maybe someone wants a certain writer for test in `gin.TestMode`.

 3. **Provide defaults for the standard `gin.Mode`s**
     If we implemented (2) we could provide defaults for the different standard `gin.Mode`s.

**Comment by a180285** [comment]
Hi @pscheid92 , I found that it's possble to overwrite the logger by
```
logger.WithLogger(func(_ *gin.Context, l zerolog.Logger) zerolog.Logger {
	return l.Output(gin.DefaultWriter).With().Logger()
}),
```

For more detail, you can check my pull request #45

**Comment by pscheid92** [comment]
Hey @a180285, excuse my late response and thank you very much for your PR! 👍 
This indeed works as a workaround! 🥳 

To me, it feels like **forcing** the API to do what we want, though:
 1. Create a logger with default output `zerolog.New(cfg.output)` (default `cfg.output = gin.DefaultWriter`)
 2. Overwrite the output to a `zerolog.ConsolteWriter`
 3. Overwrite the output to `gin.DefaultWriter` (done by your code snippet above)

It doesn't seem too elegant to me 😅 .

I would have expected `logger.WithWriter()` to be a shorter solution, but it doesn't work.
Step 2 overwrites it again, which looks like a bug to me.

We could try to find a more elegant and profound solution.
WDYT 🤔

**Comment by pscheid92** [comment]
@appleboy What do you think? Would you be open to the aforementioned changes?

**Comment by david-mk-lawrence** [comment]
I would also expect to be able to use `WithWriter` in order to set the writer later, but that doesn't seem to work as I would expect.

For example, using the above workaround wrapped in a function

```go
func MyDefaultLogger() logger.Option {
    return logger.WithLogger(func(_ *gin.Context, l zerolog.Logger) zerolog.Logger {
    	    return l.Output(gin.DefaultWriter).With().Logger()
    })
}
```

I would then expect to be able to do

```go
buf := &bytes.Buffer{}

logger.SetLogger(MyDefaultLogger(), logger.WithWriter(buf))
```

The buffer is empty however and logs continue to be written to `gin.DefaultWriter`. Calling `WithWriter` seems to have no effect.

**Comment by Tommy-42** [comment]
for those interested in having json structured logging instead of having the colorful log.

I found this article that explain everything : https://learninggolang.com/it5-gin-structured-logging.html
which is exactly doing what I want.
