### ISSUE TITLE
Attaching a request id to the logger

### ISSUE THREAD

**Issue by josegonzalez** [gin-contrib/logger#7]
It's a bit unclear as to how we might attach a request-id to all log messages within a request with this package - the upstream docs definitely don't help :(.

Any chance the readme docs could be updated to show how we can extend the logging info with net/http info? That will definitely help me figure out the request-id bits, though an example for that would be excellent.

**Comment by appleboy** [comment]
maybe add the attribute to get request-id from the header?

**Comment by josegonzalez** [comment]
Yeah I'm just not sure how to do that. Would you be able to help with an example :)

**Comment by appleboy** [comment]
@josegonzalez Please use the requestid middleware first. https://github.com/gin-contrib/requestid
